### ISSUE TITLE
jsv4 falsly returns true to validate

### ISSUE THREAD

**Issue by chrisbataille** [geraintluff/jsv4-php#17]
Hello,

i'm trying to use this library in Symfony context and here is the code i've been trying to run in PHPUnit : 

> $data = [
            "title"       => "hello World",
            "description" => "Hello World Description",
            "age"         => 5
        ];
        
> $schema = [
            '$schema'    => 'http://json-schema.org/draft-04/schema#',
            "title"      => "Hello World Schema",
            "type"       => "object",
            "properties" => [
                "title" => [
                    "type" => "string"
                ],
                "description" => [
                    "type" => "string"
                ],
                "age" => [
                    "type"    => "integer",
                    "minimum" => 10
                ]
            ]
        ];
        $ret = Jsv4::isValid($data, $schema);
        $this->assertFalse($ret);

Using https://json-schema-validator.herokuapp.com/index.jsp i get the expected error (numeric instance is lower than the required minimum (minimum: 10, found: 6)) but the isValid is returning true ...

Must be something i'm doing wrong ... but any help would be warmely welcomed.

**Comment by geraintluff** [comment]
For schemas, `SchemaStore` should perform some normalisation, so if you add it to there and ex
